[package]
name = "qwos"
version = "0.1.0"
edition = "2021"

[dependencies]
# WIP Pause this work since artifact dependencies currently have a bug. See https://github.com/tosc-rs/mnemos/pull/326
bootloader_api = "0.11.8"
spin = "0.9.8"
volatile = "0.6.1"
x86_64 = "0.15.1"
uart_16550 = "0.3.1"
pic8259 = "0.11.0"
pc-keyboard = "0.8.0"

[build-dependencies]
bootloader = "0.11"
test-kernel = {path = "kernel", artifact = "bin", target = "x86_64-unknown-none"}

[workspace]
members = ["kernel"]

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false